[phases.setup]
nixPkgs = ["nodejs", "nodePackages.npm"]

[phases.install]
cmds = [
  "npm install",
  "npm run install-all"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm run start:prod"
